# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.Switzerland))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 560))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 260))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 560))
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Racer = QtWidgets.QWidget()
        self.Tab_Racer.setToolTip("")
        self.Tab_Racer.setAccessibleName("")
        self.Tab_Racer.setObjectName("Tab_Racer")
        self.scrollArea = QtWidgets.QScrollArea(self.Tab_Racer)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 261, 531))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.L_racerlist = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.L_racerlist.setGeometry(QtCore.QRect(0, 0, 256, 491))
        self.L_racerlist.setObjectName("L_racerlist")
        item = QtWidgets.QListWidgetItem()
        self.L_racerlist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.L_racerlist.addItem(item)
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 490, 261, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget = QtWidgets.QWidget(self.Tab_Racer)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 0, 531, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.R_lastname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_lastname.setObjectName("R_lastname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.R_lastname)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.R_firstname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_firstname.setObjectName("R_firstname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.R_firstname)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.R_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_number.setObjectName("R_number")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.R_number)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.R_transponder = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_transponder.setObjectName("R_transponder")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.R_transponder)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.tabWidget.addTab(self.Tab_Racer, "")
        self.Tab_race = QtWidgets.QWidget()
        self.Tab_race.setObjectName("Tab_race")
        self.tabWidget.addTab(self.Tab_race, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFfff = QtWidgets.QMenu(self.menubar)
        self.menuFfff.setObjectName("menuFfff")
        self.menuConcurrents = QtWidgets.QMenu(self.menubar)
        self.menuConcurrents.setObjectName("menuConcurrents")
        self.menuCourses = QtWidgets.QMenu(self.menubar)
        self.menuCourses.setObjectName("menuCourses")
        self.menuR_sultats = QtWidgets.QMenu(self.menubar)
        self.menuR_sultats.setObjectName("menuR_sultats")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setShortcut("Ctrl+Q")
        self.actionQuitter.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionNouvelle_Course = QtWidgets.QAction(MainWindow)
        self.actionNouvelle_Course.setObjectName("actionNouvelle_Course")
        self.actionOuvrire = QtWidgets.QAction(MainWindow)
        self.actionOuvrire.setObjectName("actionOuvrire")
        self.actionEnregister = QtWidgets.QAction(MainWindow)
        self.actionEnregister.setObjectName("actionEnregister")
        self.actionEnregistrer_Sous = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_Sous.setObjectName("actionEnregistrer_Sous")
        self.menuFfff.addSeparator()
        self.menuFfff.addSeparator()
        self.menuFfff.addAction(self.actionNouvelle_Course)
        self.menuFfff.addAction(self.actionOuvrire)
        self.menuFfff.addAction(self.actionEnregister)
        self.menuFfff.addAction(self.actionEnregistrer_Sous)
        self.menuFfff.addSeparator()
        self.menuFfff.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFfff.menuAction())
        self.menubar.addAction(self.menuConcurrents.menuAction())
        self.menubar.addAction(self.menuCourses.menuAction())
        self.menubar.addAction(self.menuR_sultats.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RaceChrono (c) Yves Huguenin 2018"))
        __sortingEnabled = self.L_racerlist.isSortingEnabled()
        self.L_racerlist.setSortingEnabled(False)
        item = self.L_racerlist.item(0)
        item.setText(_translate("MainWindow", "Racer 1"))
        item = self.L_racerlist.item(1)
        item.setText(_translate("MainWindow", "Racer 2"))
        self.L_racerlist.setSortingEnabled(__sortingEnabled)
        self.toolButton.setText(_translate("MainWindow", "Add"))
        self.label.setText(_translate("MainWindow", "Nom"))
        self.R_lastname.setText(_translate("MainWindow", "R_LastName"))
        self.label_6.setText(_translate("MainWindow", "Prénom"))
        self.R_firstname.setText(_translate("MainWindow", "R_FirstName"))
        self.label_8.setText(_translate("MainWindow", "Numéro course"))
        self.R_number.setText(_translate("MainWindow", "R_Number"))
        self.label_7.setText(_translate("MainWindow", "Transpondeur"))
        self.R_transponder.setText(_translate("MainWindow", "R_Transponder"))
        self.label_9.setText(_translate("MainWindow", "Catégorie"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Racer), _translate("MainWindow", "Concurrents"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_race), _translate("MainWindow", "Courses"))
        self.menuFfff.setTitle(_translate("MainWindow", "Fichier"))
        self.menuConcurrents.setTitle(_translate("MainWindow", "&Concurrents"))
        self.menuCourses.setTitle(_translate("MainWindow", "Co&urses"))
        self.menuR_sultats.setTitle(_translate("MainWindow", "R&ésultats"))
        self.actionQuitter.setText(_translate("MainWindow", "&Quitter"))
        self.actionQuitter.setWhatsThis(_translate("MainWindow", "Quit le programme"))
        self.actionNouvelle_Course.setText(_translate("MainWindow", "&Nouvelle Course"))
        self.actionOuvrire.setText(_translate("MainWindow", "&Ouvrire"))
        self.actionEnregister.setText(_translate("MainWindow", "&Enregister"))
        self.actionEnregistrer_Sous.setText(_translate("MainWindow", "Enregistrer &Sous"))

