# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defGui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.Switzerland))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tab_Container = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab_Container.setGeometry(QtCore.QRect(0, 0, 800, 560))
        self.Tab_Container.setMinimumSize(QtCore.QSize(800, 260))
        self.Tab_Container.setMaximumSize(QtCore.QSize(800, 560))
        self.Tab_Container.setToolTip("")
        self.Tab_Container.setStatusTip("")
        self.Tab_Container.setAccessibleName("")
        self.Tab_Container.setAccessibleDescription("")
        self.Tab_Container.setObjectName("Tab_Container")
        self.T_Racer = QtWidgets.QWidget()
        self.T_Racer.setToolTip("")
        self.T_Racer.setAccessibleName("")
        self.T_Racer.setObjectName("T_Racer")
        self.scrollArea = QtWidgets.QScrollArea(self.T_Racer)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 261, 531))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.L_racerlist = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.L_racerlist.setGeometry(QtCore.QRect(0, 0, 256, 491))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.L_racerlist.setFont(font)
        self.L_racerlist.setMouseTracking(True)
        self.L_racerlist.setAcceptDrops(True)
        self.L_racerlist.setStyleSheet("font: 10pt \"Bitstream Charter\";")
        self.L_racerlist.setInputMethodHints(QtCore.Qt.ImhPreferLatin)
        self.L_racerlist.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.L_racerlist.setProperty("isWrapping", False)
        self.L_racerlist.setViewMode(QtWidgets.QListView.ListMode)
        self.L_racerlist.setModelColumn(0)
        self.L_racerlist.setObjectName("L_racerlist")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 490, 261, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(6, 0, 6, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setToolTip("")
        self.label_2.setStatusTip("")
        self.label_2.setAccessibleName("")
        self.label_2.setAccessibleDescription("")
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.findNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.findNumber.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setKerning(True)
        self.findNumber.setFont(font)
        self.findNumber.setMouseTracking(True)
        self.findNumber.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.findNumber.setAcceptDrops(False)
        self.findNumber.setToolTip("")
        self.findNumber.setStatusTip("")
        self.findNumber.setAccessibleName("")
        self.findNumber.setAccessibleDescription("")
        self.findNumber.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.findNumber.setInputMask("")
        self.findNumber.setText("")
        self.findNumber.setMaxLength(5)
        self.findNumber.setPlaceholderText("")
        self.findNumber.setObjectName("findNumber")
        self.horizontalLayout.addWidget(self.findNumber)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.RB_Add = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.RB_Add.setToolTip("")
        self.RB_Add.setStatusTip("")
        self.RB_Add.setAccessibleName("")
        self.RB_Add.setAccessibleDescription("")
        self.RB_Add.setShortcut("")
        self.RB_Add.setObjectName("RB_Add")
        self.gridLayout.addWidget(self.RB_Add, 0, 0, 1, 1)
        self.RB_Del = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.RB_Del.setObjectName("RB_Del")
        self.gridLayout.addWidget(self.RB_Del, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget = QtWidgets.QWidget(self.T_Racer)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 0, 1131, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.R_lastname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_lastname.setMinimumSize(QtCore.QSize(420, 0))
        self.R_lastname.setText("")
        self.R_lastname.setObjectName("R_lastname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.R_lastname)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.R_firstname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_firstname.setMinimumSize(QtCore.QSize(420, 0))
        self.R_firstname.setText("")
        self.R_firstname.setObjectName("R_firstname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.R_firstname)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.R_address = QtWidgets.QTextEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_address.sizePolicy().hasHeightForWidth())
        self.R_address.setSizePolicy(sizePolicy)
        self.R_address.setMinimumSize(QtCore.QSize(420, 40))
        self.R_address.setBaseSize(QtCore.QSize(420, 40))
        self.R_address.setToolTip("")
        self.R_address.setStatusTip("")
        self.R_address.setAccessibleName("")
        self.R_address.setAccessibleDescription("")
        self.R_address.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.R_address.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.R_address.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.R_address.setDocumentTitle("")
        self.R_address.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.R_address.setAcceptRichText(False)
        self.R_address.setPlaceholderText("")
        self.R_address.setProperty("inputMask", "")
        self.R_address.setProperty("text", "R_Address")
        self.R_address.setObjectName("R_address")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.R_address)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.R_Npa = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_Npa.sizePolicy().hasHeightForWidth())
        self.R_Npa.setSizePolicy(sizePolicy)
        self.R_Npa.setToolTip("")
        self.R_Npa.setStatusTip("")
        self.R_Npa.setAccessibleName("")
        self.R_Npa.setAccessibleDescription("")
        self.R_Npa.setInputMask("")
        self.R_Npa.setText("")
        self.R_Npa.setMaxLength(9)
        self.R_Npa.setObjectName("R_Npa")
        self.horizontalLayout_2.addWidget(self.R_Npa)
        self.R_City = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_City.setMinimumSize(QtCore.QSize(290, 0))
        self.R_City.setText("")
        self.R_City.setObjectName("R_City")
        self.horizontalLayout_2.addWidget(self.R_City)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.R_Pays = QtWidgets.QComboBox(self.formLayoutWidget)
        self.R_Pays.setObjectName("R_Pays")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.R_Pays)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.R_date = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.R_date.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhPreferNumbers)
        self.R_date.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7918, 1, 1), QtCore.QTime(23, 59, 59)))
        self.R_date.setMaximumDate(QtCore.QDate(7918, 1, 1))
        self.R_date.setCalendarPopup(True)
        self.R_date.setObjectName("R_date")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.R_date)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.R_telephone = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_telephone.sizePolicy().hasHeightForWidth())
        self.R_telephone.setSizePolicy(sizePolicy)
        self.R_telephone.setMouseTracking(True)
        self.R_telephone.setToolTip("")
        self.R_telephone.setStatusTip("")
        self.R_telephone.setAccessibleName("")
        self.R_telephone.setAccessibleDescription("")
        self.R_telephone.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.R_telephone.setText("+// ")
        self.R_telephone.setPlaceholderText("")
        self.R_telephone.setObjectName("R_telephone")
        self.horizontalLayout_3.addWidget(self.R_telephone)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.R_Urgence = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_Urgence.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.R_Urgence.setInputMask("+##/####/### ####")
        self.R_Urgence.setText("+// ")
        self.R_Urgence.setObjectName("R_Urgence")
        self.horizontalLayout_3.addWidget(self.R_Urgence)
        self.formLayout.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.R_EMail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_EMail.setMinimumSize(QtCore.QSize(420, 0))
        self.R_EMail.setToolTip("")
        self.R_EMail.setStatusTip("")
        self.R_EMail.setAccessibleName("")
        self.R_EMail.setAccessibleDescription("")
        self.R_EMail.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.R_EMail.setInputMask("")
        self.R_EMail.setText("")
        self.R_EMail.setPlaceholderText("")
        self.R_EMail.setObjectName("R_EMail")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.R_EMail)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.R_brandMenu = QtWidgets.QComboBox(self.formLayoutWidget)
        self.R_brandMenu.setToolTip("")
        self.R_brandMenu.setStatusTip("")
        self.R_brandMenu.setAccessibleName("")
        self.R_brandMenu.setAccessibleDescription("")
        self.R_brandMenu.setEditable(False)
        self.R_brandMenu.setCurrentText("")
        self.R_brandMenu.setObjectName("R_brandMenu")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.R_brandMenu)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.R_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_number.setToolTip("")
        self.R_number.setStatusTip("")
        self.R_number.setAccessibleName("")
        self.R_number.setAccessibleDescription("")
        self.R_number.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly)
        self.R_number.setText("")
        self.R_number.setMaxLength(5)
        self.R_number.setObjectName("R_number")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.R_number)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.R_licences = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_licences.sizePolicy().hasHeightForWidth())
        self.R_licences.setSizePolicy(sizePolicy)
        self.R_licences.setMinimumSize(QtCore.QSize(420, 0))
        self.R_licences.setToolTip("")
        self.R_licences.setStatusTip("")
        self.R_licences.setAccessibleName("")
        self.R_licences.setAccessibleDescription("")
        self.R_licences.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.R_licences.setInputMask("")
        self.R_licences.setText("")
        self.R_licences.setObjectName("R_licences")
        self.formLayout.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.R_licences)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(25, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.R_transponder = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.R_transponder.setToolTip("")
        self.R_transponder.setStatusTip("")
        self.R_transponder.setAccessibleName("")
        self.R_transponder.setAccessibleDescription("")
        self.R_transponder.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.R_transponder.setText("")
        self.R_transponder.setMaxLength(12)
        self.R_transponder.setObjectName("R_transponder")
        self.formLayout.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.R_transponder)
        self.Tab_Container.addTab(self.T_Racer, "")
        self.T_Category = QtWidgets.QWidget()
        self.T_Category.setObjectName("T_Category")
        self.Tab_Container.addTab(self.T_Category, "")
        self.T_Racer_Race = QtWidgets.QWidget()
        self.T_Racer_Race.setObjectName("T_Racer_Race")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.T_Racer_Race)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 490, 261, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(6, 0, 6, 0)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_33.setEnabled(True)
        self.label_33.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_33.setFont(font)
        self.label_33.setToolTip("")
        self.label_33.setStatusTip("")
        self.label_33.setAccessibleName("")
        self.label_33.setAccessibleDescription("")
        self.label_33.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_7.addWidget(self.label_33)
        self.RR_findNumber = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.RR_findNumber.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setKerning(True)
        self.RR_findNumber.setFont(font)
        self.RR_findNumber.setMouseTracking(True)
        self.RR_findNumber.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RR_findNumber.setAcceptDrops(False)
        self.RR_findNumber.setToolTip("")
        self.RR_findNumber.setStatusTip("")
        self.RR_findNumber.setAccessibleName("")
        self.RR_findNumber.setAccessibleDescription("")
        self.RR_findNumber.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.RR_findNumber.setInputMask("")
        self.RR_findNumber.setText("")
        self.RR_findNumber.setMaxLength(5)
        self.RR_findNumber.setPlaceholderText("")
        self.RR_findNumber.setObjectName("RR_findNumber")
        self.horizontalLayout_7.addWidget(self.RR_findNumber)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.L_RList = QtWidgets.QListWidget(self.T_Racer_Race)
        self.L_RList.setGeometry(QtCore.QRect(0, 0, 256, 491))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.L_RList.setFont(font)
        self.L_RList.setMouseTracking(True)
        self.L_RList.setAcceptDrops(True)
        self.L_RList.setStyleSheet("font: 10pt \"Bitstream Charter\";")
        self.L_RList.setInputMethodHints(QtCore.Qt.ImhPreferLatin)
        self.L_RList.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.L_RList.setProperty("isWrapping", False)
        self.L_RList.setViewMode(QtWidgets.QListView.ListMode)
        self.L_RList.setModelColumn(0)
        self.L_RList.setObjectName("L_RList")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.T_Racer_Race)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(260, 0, 1131, 521))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.RR_lastname = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.RR_lastname.setMinimumSize(QtCore.QSize(420, 0))
        self.RR_lastname.setMouseTracking(False)
        self.RR_lastname.setAcceptDrops(False)
        self.RR_lastname.setToolTip("")
        self.RR_lastname.setStatusTip("")
        self.RR_lastname.setAccessibleName("")
        self.RR_lastname.setAccessibleDescription("")
        self.RR_lastname.setInputMask("")
        self.RR_lastname.setText("R_LastName")
        self.RR_lastname.setFrame(False)
        self.RR_lastname.setReadOnly(True)
        self.RR_lastname.setPlaceholderText("")
        self.RR_lastname.setObjectName("RR_lastname")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.RR_lastname)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.RR_firstname = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.RR_firstname.setMinimumSize(QtCore.QSize(420, 0))
        self.RR_firstname.setMouseTracking(False)
        self.RR_firstname.setAcceptDrops(False)
        self.RR_firstname.setToolTip("")
        self.RR_firstname.setStatusTip("")
        self.RR_firstname.setAccessibleName("")
        self.RR_firstname.setAccessibleDescription("")
        self.RR_firstname.setText("R_FirstName")
        self.RR_firstname.setFrame(False)
        self.RR_firstname.setReadOnly(True)
        self.RR_firstname.setPlaceholderText("")
        self.RR_firstname.setObjectName("RR_firstname")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.RR_firstname)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RR_Npa = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RR_Npa.sizePolicy().hasHeightForWidth())
        self.RR_Npa.setSizePolicy(sizePolicy)
        self.RR_Npa.setMouseTracking(False)
        self.RR_Npa.setAcceptDrops(False)
        self.RR_Npa.setToolTip("")
        self.RR_Npa.setStatusTip("")
        self.RR_Npa.setAccessibleName("")
        self.RR_Npa.setAccessibleDescription("")
        self.RR_Npa.setInputMask("")
        self.RR_Npa.setText("R_Npa")
        self.RR_Npa.setMaxLength(9)
        self.RR_Npa.setFrame(False)
        self.RR_Npa.setReadOnly(True)
        self.RR_Npa.setPlaceholderText("")
        self.RR_Npa.setObjectName("RR_Npa")
        self.horizontalLayout_8.addWidget(self.RR_Npa)
        self.RR_City = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.RR_City.setMinimumSize(QtCore.QSize(290, 0))
        self.RR_City.setMouseTracking(False)
        self.RR_City.setAcceptDrops(False)
        self.RR_City.setToolTip("")
        self.RR_City.setStatusTip("")
        self.RR_City.setAccessibleName("")
        self.RR_City.setAccessibleDescription("")
        self.RR_City.setInputMask("")
        self.RR_City.setText("R_Localité")
        self.RR_City.setFrame(False)
        self.RR_City.setReadOnly(True)
        self.RR_City.setPlaceholderText("")
        self.RR_City.setObjectName("RR_City")
        self.horizontalLayout_8.addWidget(self.RR_City)
        self.formLayout_3.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.RR_Pays = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.RR_Pays.setToolTip("")
        self.RR_Pays.setStatusTip("")
        self.RR_Pays.setAccessibleName("")
        self.RR_Pays.setAccessibleDescription("")
        self.RR_Pays.setObjectName("RR_Pays")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.RR_Pays)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.RR_date = QtWidgets.QDateEdit(self.formLayoutWidget_3)
        self.RR_date.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RR_date.setToolTip("")
        self.RR_date.setStatusTip("")
        self.RR_date.setAccessibleName("")
        self.RR_date.setAccessibleDescription("")
        self.RR_date.setInputMethodHints(QtCore.Qt.ImhNone)
        self.RR_date.setFrame(False)
        self.RR_date.setReadOnly(True)
        self.RR_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.RR_date.setSpecialValueText("")
        self.RR_date.setKeyboardTracking(False)
        self.RR_date.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7918, 1, 1), QtCore.QTime(23, 59, 59)))
        self.RR_date.setMaximumDate(QtCore.QDate(7918, 1, 1))
        self.RR_date.setCalendarPopup(False)
        self.RR_date.setObjectName("RR_date")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.RR_date)
        self.label_45 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_45.setObjectName("label_45")
        self.formLayout_3.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.RR_number = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.RR_number.setMouseTracking(False)
        self.RR_number.setAcceptDrops(False)
        self.RR_number.setToolTip("")
        self.RR_number.setStatusTip("")
        self.RR_number.setAccessibleName("")
        self.RR_number.setAccessibleDescription("")
        self.RR_number.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly)
        self.RR_number.setInputMask("")
        self.RR_number.setText("00000")
        self.RR_number.setMaxLength(5)
        self.RR_number.setFrame(False)
        self.RR_number.setReadOnly(True)
        self.RR_number.setPlaceholderText("")
        self.RR_number.setObjectName("RR_number")
        self.formLayout_3.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.RR_number)
        self.label_46 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_46.setObjectName("label_46")
        self.formLayout_3.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.RR_licences = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RR_licences.sizePolicy().hasHeightForWidth())
        self.RR_licences.setSizePolicy(sizePolicy)
        self.RR_licences.setMinimumSize(QtCore.QSize(420, 0))
        self.RR_licences.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RR_licences.setMouseTracking(False)
        self.RR_licences.setAcceptDrops(False)
        self.RR_licences.setToolTip("")
        self.RR_licences.setStatusTip("")
        self.RR_licences.setAccessibleName("")
        self.RR_licences.setAccessibleDescription("")
        self.RR_licences.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.RR_licences.setInputMask("")
        self.RR_licences.setText("Licences")
        self.RR_licences.setFrame(False)
        self.RR_licences.setReadOnly(True)
        self.RR_licences.setPlaceholderText("")
        self.RR_licences.setObjectName("RR_licences")
        self.formLayout_3.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.RR_licences)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(21, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_47 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_47.setObjectName("label_47")
        self.formLayout_3.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.RR_transponder = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.RR_transponder.setToolTip("")
        self.RR_transponder.setStatusTip("")
        self.RR_transponder.setAccessibleName("")
        self.RR_transponder.setAccessibleDescription("")
        self.RR_transponder.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.RR_transponder.setText("0000000000")
        self.RR_transponder.setMaxLength(12)
        self.RR_transponder.setPlaceholderText("")
        self.RR_transponder.setObjectName("RR_transponder")
        self.formLayout_3.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.RR_transponder)
        self.label_48 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_48.setObjectName("label_48")
        self.formLayout_3.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.RR_Categorie = QtWidgets.QTreeWidget(self.formLayoutWidget_3)
        self.RR_Categorie.setToolTip("")
        self.RR_Categorie.setStatusTip("")
        self.RR_Categorie.setAccessibleName("")
        self.RR_Categorie.setAccessibleDescription("")
        self.RR_Categorie.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.RR_Categorie.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.RR_Categorie.setHeaderHidden(False)
        self.RR_Categorie.setExpandsOnDoubleClick(True)
        self.RR_Categorie.setObjectName("RR_Categorie")
        item_0 = QtWidgets.QTreeWidgetItem(self.RR_Categorie)
        self.RR_Categorie.topLevelItem(0).setText(0, "MX1")
        item_0.setToolTip(0, "")
        item_0.setStatusTip(0, "")
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.RR_Categorie.topLevelItem(0).child(0).setText(0, "Top")
        item_1.setToolTip(0, "")
        item_1.setStatusTip(0, "")
        item_1.setWhatsThis(0, "")
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.RR_Categorie.topLevelItem(0).child(1).setText(0, "Pro")
        item_1.setToolTip(0, "")
        item_1.setStatusTip(0, "")
        item_1.setWhatsThis(0, "")
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.RR_Categorie.topLevelItem(0).child(2).setText(0, "Cartons")
        item_1.setToolTip(0, "")
        item_1.setStatusTip(0, "")
        item_1.setWhatsThis(0, "")
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.RR_Categorie)
        self.RR_Categorie.topLevelItem(1).setText(0, "Mini")
        item_0.setToolTip(0, "")
        item_0.setStatusTip(0, "")
        item_0.setWhatsThis(0, "")
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.RR_Categorie.topLevelItem(1).child(0).setText(0, "Mini")
        item_1.setToolTip(0, "")
        item_1.setStatusTip(0, "")
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        self.formLayout_3.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.RR_Categorie)
        self.Tab_Container.addTab(self.T_Racer_Race, "")
        self.T_RaceModel = QtWidgets.QWidget()
        self.T_RaceModel.setObjectName("T_RaceModel")
        self.Tab_Container.addTab(self.T_RaceModel, "")
        self.T_Race = QtWidgets.QWidget()
        self.T_Race.setObjectName("T_Race")
        self.toolBox = QtWidgets.QToolBox(self.T_Race)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 821, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolBox.setFont(font)
        self.toolBox.setToolTip("")
        self.toolBox.setStatusTip("")
        self.toolBox.setAccessibleName("")
        self.toolBox.setAccessibleDescription("")
        self.toolBox.setObjectName("toolBox")
        self.P_Race = QtWidgets.QWidget()
        self.P_Race.setGeometry(QtCore.QRect(0, 0, 821, 477))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P_Race.sizePolicy().hasHeightForWidth())
        self.P_Race.setSizePolicy(sizePolicy)
        self.P_Race.setToolTip("")
        self.P_Race.setStatusTip("")
        self.P_Race.setAccessibleName("")
        self.P_Race.setAccessibleDescription("")
        self.P_Race.setObjectName("P_Race")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.P_Race)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 801, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_P_Race = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_P_Race.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_P_Race.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_P_Race.setSpacing(1)
        self.verticalLayout_P_Race.setObjectName("verticalLayout_P_Race")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PB_TimeRace = QtWidgets.QProgressBar(self.verticalLayoutWidget_2)
        self.PB_TimeRace.setEnabled(True)
        self.PB_TimeRace.setToolTip("")
        self.PB_TimeRace.setStatusTip("")
        self.PB_TimeRace.setAccessibleName("")
        self.PB_TimeRace.setAccessibleDescription("")
        self.PB_TimeRace.setMaximum(1)
        self.PB_TimeRace.setProperty("value", 1)
        self.PB_TimeRace.setTextVisible(True)
        self.PB_TimeRace.setFormat("Waiting for start")
        self.PB_TimeRace.setObjectName("PB_TimeRace")
        self.horizontalLayout_4.addWidget(self.PB_TimeRace)
        self.B_Define = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.B_Define.setMaximumSize(QtCore.QSize(20, 16777215))
        self.B_Define.setToolTip("")
        self.B_Define.setStatusTip("")
        self.B_Define.setAccessibleName("")
        self.B_Define.setAccessibleDescription("")
        self.B_Define.setFrame(True)
        self.B_Define.setObjectName("B_Define")
        self.B_Define.addItem("")
        self.B_Define.addItem("")
        self.B_Define.addItem("")
        self.horizontalLayout_4.addWidget(self.B_Define)
        self.B_Start = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.B_Start.setToolTip("")
        self.B_Start.setStatusTip("")
        self.B_Start.setAccessibleName("")
        self.B_Start.setAccessibleDescription("")
        self.B_Start.setObjectName("B_Start")
        self.horizontalLayout_4.addWidget(self.B_Start)
        self.B_Stop = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.B_Stop.setEnabled(False)
        self.B_Stop.setToolTip("")
        self.B_Stop.setStatusTip("")
        self.B_Stop.setAccessibleName("")
        self.B_Stop.setAccessibleDescription("")
        self.B_Stop.setObjectName("B_Stop")
        self.horizontalLayout_4.addWidget(self.B_Stop)
        self.verticalLayout_P_Race.addLayout(self.horizontalLayout_4)
        self.R_RaceLive = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.R_RaceLive.setToolTip("")
        self.R_RaceLive.setStatusTip("")
        self.R_RaceLive.setAccessibleName("")
        self.R_RaceLive.setAccessibleDescription("")
        self.R_RaceLive.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R_RaceLive.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.R_RaceLive.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.R_RaceLive.setTabKeyNavigation(False)
        self.R_RaceLive.setProperty("showDropIndicator", False)
        self.R_RaceLive.setDragDropOverwriteMode(False)
        self.R_RaceLive.setAlternatingRowColors(True)
        self.R_RaceLive.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.R_RaceLive.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.R_RaceLive.setRowCount(0)
        self.R_RaceLive.setColumnCount(7)
        self.R_RaceLive.setObjectName("R_RaceLive")
        item = QtWidgets.QTableWidgetItem()
        item.setText("Sorting")
        self.R_RaceLive.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R_RaceLive.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive.setHorizontalHeaderItem(6, item)
        self.R_RaceLive.horizontalHeader().setDefaultSectionSize(100)
        self.R_RaceLive.horizontalHeader().setSortIndicatorShown(False)
        self.R_RaceLive.horizontalHeader().setStretchLastSection(False)
        self.R_RaceLive.verticalHeader().setDefaultSectionSize(15)
        self.R_RaceLive.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_P_Race.addWidget(self.R_RaceLive)
        self.toolBox.addItem(self.P_Race, "")
        self.P_Laptime = QtWidgets.QWidget()
        self.P_Laptime.setGeometry(QtCore.QRect(0, 0, 821, 477))
        self.P_Laptime.setObjectName("P_Laptime")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.P_Laptime)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 791, 471))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_P_Laptime = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_P_Laptime.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_P_Laptime.setSpacing(1)
        self.verticalLayout_P_Laptime.setObjectName("verticalLayout_P_Laptime")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PB_TimeRace_2 = QtWidgets.QProgressBar(self.verticalLayoutWidget_3)
        self.PB_TimeRace_2.setEnabled(True)
        self.PB_TimeRace_2.setToolTip("")
        self.PB_TimeRace_2.setStatusTip("")
        self.PB_TimeRace_2.setAccessibleName("")
        self.PB_TimeRace_2.setAccessibleDescription("")
        self.PB_TimeRace_2.setMaximum(1)
        self.PB_TimeRace_2.setProperty("value", 1)
        self.PB_TimeRace_2.setTextVisible(True)
        self.PB_TimeRace_2.setFormat("Waiting for start")
        self.PB_TimeRace_2.setObjectName("PB_TimeRace_2")
        self.horizontalLayout_5.addWidget(self.PB_TimeRace_2)
        self.B_Define_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.B_Define_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.B_Define_2.setToolTip("")
        self.B_Define_2.setStatusTip("")
        self.B_Define_2.setAccessibleName("")
        self.B_Define_2.setAccessibleDescription("")
        self.B_Define_2.setFrame(True)
        self.B_Define_2.setObjectName("B_Define_2")
        self.B_Define_2.addItem("")
        self.B_Define_2.addItem("")
        self.B_Define_2.addItem("")
        self.horizontalLayout_5.addWidget(self.B_Define_2)
        self.B_Stop_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.B_Stop_2.setEnabled(False)
        self.B_Stop_2.setToolTip("")
        self.B_Stop_2.setStatusTip("")
        self.B_Stop_2.setAccessibleName("")
        self.B_Stop_2.setAccessibleDescription("")
        self.B_Stop_2.setObjectName("B_Stop_2")
        self.horizontalLayout_5.addWidget(self.B_Stop_2)
        self.B_Start_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.B_Start_2.setToolTip("")
        self.B_Start_2.setStatusTip("")
        self.B_Start_2.setAccessibleName("")
        self.B_Start_2.setAccessibleDescription("")
        self.B_Start_2.setObjectName("B_Start_2")
        self.horizontalLayout_5.addWidget(self.B_Start_2)
        self.verticalLayout_P_Laptime.addLayout(self.horizontalLayout_5)
        self.R_RaceLive_2 = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.R_RaceLive_2.setToolTip("")
        self.R_RaceLive_2.setStatusTip("")
        self.R_RaceLive_2.setAccessibleName("")
        self.R_RaceLive_2.setAccessibleDescription("")
        self.R_RaceLive_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R_RaceLive_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.R_RaceLive_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.R_RaceLive_2.setTabKeyNavigation(False)
        self.R_RaceLive_2.setProperty("showDropIndicator", False)
        self.R_RaceLive_2.setDragDropOverwriteMode(False)
        self.R_RaceLive_2.setAlternatingRowColors(True)
        self.R_RaceLive_2.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.R_RaceLive_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.R_RaceLive_2.setRowCount(0)
        self.R_RaceLive_2.setColumnCount(7)
        self.R_RaceLive_2.setObjectName("R_RaceLive_2")
        item = QtWidgets.QTableWidgetItem()
        item.setText("Sorting")
        self.R_RaceLive_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R_RaceLive_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.R_RaceLive_2.setHorizontalHeaderItem(6, item)
        self.R_RaceLive_2.horizontalHeader().setDefaultSectionSize(100)
        self.R_RaceLive_2.horizontalHeader().setSortIndicatorShown(False)
        self.R_RaceLive_2.horizontalHeader().setStretchLastSection(False)
        self.R_RaceLive_2.verticalHeader().setDefaultSectionSize(15)
        self.R_RaceLive_2.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_P_Laptime.addWidget(self.R_RaceLive_2)
        self.toolBox.addItem(self.P_Laptime, "")
        self.Tab_Container.addTab(self.T_Race, "")
        self.T_Results = QtWidgets.QWidget()
        self.T_Results.setObjectName("T_Results")
        self.Tab_Container.addTab(self.T_Results, "")
        self.T_Monitor = QtWidgets.QWidget()
        self.T_Monitor.setToolTip("")
        self.T_Monitor.setStatusTip("")
        self.T_Monitor.setAccessibleName("")
        self.T_Monitor.setAccessibleDescription("")
        self.T_Monitor.setObjectName("T_Monitor")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.T_Monitor)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.TM_T_passage = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TM_T_passage.sizePolicy().hasHeightForWidth())
        self.TM_T_passage.setSizePolicy(sizePolicy)
        self.TM_T_passage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TM_T_passage.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TM_T_passage.setFont(font)
        self.TM_T_passage.setToolTip("")
        self.TM_T_passage.setStatusTip("")
        self.TM_T_passage.setAccessibleName("")
        self.TM_T_passage.setAccessibleDescription("")
        self.TM_T_passage.setAutoFillBackground(False)
        self.TM_T_passage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TM_T_passage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TM_T_passage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TM_T_passage.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.TM_T_passage.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TM_T_passage.setTabKeyNavigation(False)
        self.TM_T_passage.setProperty("showDropIndicator", False)
        self.TM_T_passage.setDragDropOverwriteMode(False)
        self.TM_T_passage.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TM_T_passage.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TM_T_passage.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.TM_T_passage.setWordWrap(False)
        self.TM_T_passage.setCornerButtonEnabled(False)
        self.TM_T_passage.setRowCount(40)
        self.TM_T_passage.setObjectName("TM_T_passage")
        self.TM_T_passage.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TM_T_passage.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TM_T_passage.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TM_T_passage.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TM_T_passage.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TM_T_passage.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TM_T_passage.setHorizontalHeaderItem(5, item)
        self.TM_T_passage.horizontalHeader().setCascadingSectionResizes(False)
        self.TM_T_passage.horizontalHeader().setDefaultSectionSize(100)
        self.TM_T_passage.horizontalHeader().setMinimumSectionSize(50)
        self.TM_T_passage.horizontalHeader().setSortIndicatorShown(True)
        self.TM_T_passage.horizontalHeader().setStretchLastSection(True)
        self.TM_T_passage.verticalHeader().setVisible(False)
        self.TM_T_passage.verticalHeader().setDefaultSectionSize(10)
        self.TM_T_passage.verticalHeader().setHighlightSections(False)
        self.TM_T_passage.verticalHeader().setMinimumSectionSize(10)
        self.horizontalLayout_9.addWidget(self.TM_T_passage)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.Tab_Container.addTab(self.T_Monitor, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFfff = QtWidgets.QMenu(self.menubar)
        self.menuFfff.setObjectName("menuFfff")
        self.menuConcurrents = QtWidgets.QMenu(self.menubar)
        self.menuConcurrents.setObjectName("menuConcurrents")
        self.menuCourses = QtWidgets.QMenu(self.menubar)
        self.menuCourses.setObjectName("menuCourses")
        self.menuR_sultats = QtWidgets.QMenu(self.menubar)
        self.menuR_sultats.setObjectName("menuR_sultats")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setShortcut("Ctrl+Q")
        self.actionQuitter.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionNouvelle_Course = QtWidgets.QAction(MainWindow)
        self.actionNouvelle_Course.setObjectName("actionNouvelle_Course")
        self.actionOuvrire = QtWidgets.QAction(MainWindow)
        self.actionOuvrire.setObjectName("actionOuvrire")
        self.actionEnregister = QtWidgets.QAction(MainWindow)
        self.actionEnregister.setObjectName("actionEnregister")
        self.actionEnregistrer_Sous = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_Sous.setObjectName("actionEnregistrer_Sous")
        self.menuFfff.addSeparator()
        self.menuFfff.addSeparator()
        self.menuFfff.addAction(self.actionNouvelle_Course)
        self.menuFfff.addAction(self.actionOuvrire)
        self.menuFfff.addAction(self.actionEnregister)
        self.menuFfff.addAction(self.actionEnregistrer_Sous)
        self.menuFfff.addSeparator()
        self.menuFfff.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFfff.menuAction())
        self.menubar.addAction(self.menuConcurrents.menuAction())
        self.menubar.addAction(self.menuCourses.menuAction())
        self.menubar.addAction(self.menuR_sultats.menuAction())

        self.retranslateUi(MainWindow)
        self.Tab_Container.setCurrentIndex(4)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(6)
        self.RB_Add.released.connect(MainWindow.update)
        self.Tab_Container.currentChanged['int'].connect(MainWindow.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RaceChrono (c) Yves Huguenin 2018"))
        self.label_2.setText(_translate("MainWindow", "Numéro:"))
        self.RB_Add.setText(_translate("MainWindow", "Ajouter"))
        self.RB_Del.setText(_translate("MainWindow", "Effacer"))
        self.label.setText(_translate("MainWindow", "Nom"))
        self.label_6.setText(_translate("MainWindow", "Prénom"))
        self.label_13.setText(_translate("MainWindow", "Adresse"))
        self.label_10.setText(_translate("MainWindow", "Npa/Localité"))
        self.label_14.setText(_translate("MainWindow", "Pays"))
        self.label_12.setText(_translate("MainWindow", "Date naissance"))
        self.R_date.setDisplayFormat(_translate("MainWindow", "dd MMMM yyyy"))
        self.label_15.setText(_translate("MainWindow", "Téléphones:"))
        self.label_16.setText(_translate("MainWindow", "Privé:"))
        self.R_telephone.setInputMask(_translate("MainWindow", "+##/####/### ####"))
        self.label_17.setText(_translate("MainWindow", "Urgence:"))
        self.label_3.setText(_translate("MainWindow", "E-Mail"))
        self.label_11.setText(_translate("MainWindow", "Marque"))
        self.label_8.setText(_translate("MainWindow", "Numéro course"))
        self.label_4.setText(_translate("MainWindow", "Licence(s)"))
        self.label_7.setText(_translate("MainWindow", "Transpondeur"))
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_Racer), _translate("MainWindow", "Concurrents"))
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_Category), _translate("MainWindow", "Catégories"))
        self.label_33.setText(_translate("MainWindow", "Numéro:"))
        self.label_34.setText(_translate("MainWindow", "Nom"))
        self.label_35.setText(_translate("MainWindow", "Prénom"))
        self.label_37.setText(_translate("MainWindow", "Npa/Localité"))
        self.label_38.setText(_translate("MainWindow", "Pays"))
        self.label_39.setText(_translate("MainWindow", "Date naissance"))
        self.RR_date.setDisplayFormat(_translate("MainWindow", "dd MMMM yyyy"))
        self.label_45.setText(_translate("MainWindow", "Numéro course"))
        self.label_46.setText(_translate("MainWindow", "Licence(s)"))
        self.label_47.setText(_translate("MainWindow", "Transpondeur"))
        self.label_48.setText(_translate("MainWindow", "Catégorie"))
        self.RR_Categorie.setSortingEnabled(True)
        self.RR_Categorie.headerItem().setText(0, _translate("MainWindow", "Catégories"))
        __sortingEnabled = self.RR_Categorie.isSortingEnabled()
        self.RR_Categorie.setSortingEnabled(False)
        self.RR_Categorie.setSortingEnabled(__sortingEnabled)
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_Racer_Race), _translate("MainWindow", "Participants"))
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_RaceModel), _translate("MainWindow", "Modeles Courses"))
        self.B_Define.setItemText(0, _translate("MainWindow", "Menu Options"))
        self.B_Define.setItemText(1, _translate("MainWindow", "Durée"))
        self.B_Define.setItemText(2, _translate("MainWindow", "Sauvegade des Résultats"))
        self.B_Start.setText(_translate("MainWindow", "Départ"))
        self.B_Stop.setText(_translate("MainWindow", "STOP"))
        self.R_RaceLive.setSortingEnabled(False)
        item = self.R_RaceLive.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.R_RaceLive.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Laps"))
        item = self.R_RaceLive.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Temps"))
        item = self.R_RaceLive.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dernier"))
        item = self.R_RaceLive.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Meilleur"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.P_Race), _translate("MainWindow", "Course"))
        self.B_Define_2.setItemText(0, _translate("MainWindow", "Menu Options"))
        self.B_Define_2.setItemText(1, _translate("MainWindow", "Durée"))
        self.B_Define_2.setItemText(2, _translate("MainWindow", "Sauvegade des Résultats"))
        self.B_Stop_2.setText(_translate("MainWindow", "STOP"))
        self.B_Start_2.setText(_translate("MainWindow", "Départ"))
        self.R_RaceLive_2.setSortingEnabled(False)
        item = self.R_RaceLive_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nom"))
        item = self.R_RaceLive_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Laps"))
        item = self.R_RaceLive_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Temps"))
        item = self.R_RaceLive_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dernier"))
        item = self.R_RaceLive_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Meilleur"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.P_Laptime), _translate("MainWindow", "Laptime"))
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_Race), _translate("MainWindow", "Courses"))
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_Results), _translate("MainWindow", "Résultats"))
        item = self.TM_T_passage.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Decode / Pos."))
        item = self.TM_T_passage.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TimeCode "))
        item = self.TM_T_passage.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Transpondeur"))
        item = self.TM_T_passage.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LapTime"))
        item = self.TM_T_passage.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Numéro"))
        item = self.TM_T_passage.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Nom,Prénom Concurrent"))
        self.Tab_Container.setTabText(self.Tab_Container.indexOf(self.T_Monitor), _translate("MainWindow", "Moniteur"))
        self.menuFfff.setTitle(_translate("MainWindow", "Fichier"))
        self.menuConcurrents.setTitle(_translate("MainWindow", "&Concurrents"))
        self.menuCourses.setTitle(_translate("MainWindow", "Co&urses"))
        self.menuR_sultats.setTitle(_translate("MainWindow", "R&ésultats"))
        self.actionQuitter.setText(_translate("MainWindow", "&Quitter"))
        self.actionQuitter.setWhatsThis(_translate("MainWindow", "Quit le programme"))
        self.actionNouvelle_Course.setText(_translate("MainWindow", "&Nouvelle Course"))
        self.actionOuvrire.setText(_translate("MainWindow", "&Ouvrire"))
        self.actionEnregister.setText(_translate("MainWindow", "&Enregister"))
        self.actionEnregistrer_Sous.setText(_translate("MainWindow", "Enregistrer &Sous"))

